### ISSUE TITLE
Execute from command line 

### ISSUE THREAD

**Issue by extremety1989** [Faless/gd-udp-dtls-example#1]
i changed from Control to SceneTree to be able execute the script from command line,but i got nothing executed .
It prints false ,what is the issue here ?

func _init():
	if udp_server.is_connection_available():
		print("true")
	else:
		print("false")

**Comment by Faless** [comment]
The script do not automatically start the UDP/DTLS server (see `_on_Host_pressed`)
`_init()` is only called once, so it makes no sense to do the check there.

Use this diff for a standalone version:
```diff
diff --git a/script/server.gd b/script/server.gd
index f0dc1f6..bff3d64 100644
--- a/script/server.gd
+++ b/script/server.gd
@@ -1,4 +1,4 @@
-extends Control
+extends SceneTree
 
 const PORT = 4433
 const ADDR = "127.0.0.1"
@@ -11,11 +11,14 @@ var idx = 0
 var udp_server = UDPServer.new()
 var dtls_server = DTLSServer.new()
 
+func _init():
+       _on_Host_pressed()
+       connect("idle_frame", self, "process")
+
 func _log(msg):
        print(msg)
-       $H/logs.text += str(msg) + "\n"
 
-func _process(delta):
+func process():
        if udp_server.is_connection_available():
                # Try to perform DTLS handshake
                _take_connection()
```

**Comment by extremety1989** [comment]
@Faless thank you for response, i made loop run but i got is_connection_available() to False, why is that issue ?

`extends SceneTree

const PORT = 4433
const ADDR = "127.0.0.1"


var dtls = true
var clients = {}
var idx = 0
var udp_server = UDPServer.new()
var dtls_server = DTLSServer.new()



func _init():
		var key = load("key.key") 
		var cert = load("cert.crt")
		udp_server.listen(4433)
		dtls_server.setup(key, cert, null)
		connect("idle_frame", self, "process")
		

func process():
	print(udp_server.is_connection_available())
	if udp_server.is_connection_available():
		print("oj")
		_take_connection()
	# Clean stale clients
	var to_rem = []
	for k in clients:
		if not _poll_client(clients[k]):
			to_rem.append(k)
	for k in to_rem:
		clients.erase(k)

func _take_connection():
	var key = str(idx)
	idx += 1
	print("take connection")
	if not (key in clients):
		print("Taking connection: %s" % key)
		# Get the UDP connection
		var conn = udp_server.take_connection()
		if dtls:
			# Try to handshake with the UDP peer
			var secure = dtls_server.take_connection(conn)
			if secure.get_status() != PacketPeerDTLS.STATUS_HANDSHAKING:
				idx -= 1
				print("Handshake failed")
			else:
				# 50% of the time under regular conditions (client connecting with no cookie set)
				print("Handshaking with client")
				clients[key] = secure
		else:
			clients[key] = conn

func _poll_client(c):
	if dtls:
		c.poll()
		var status = c.get_status()
		if status != PacketPeerDTLS.STATUS_CONNECTED and status != PacketPeerDTLS.STATUS_HANDSHAKING:
			return false
		if status == PacketPeerDTLS.STATUS_HANDSHAKING:
			return true
	while c.get_available_packet_count() > 0:
		var pkt = c.get_packet()
		if dtls:
			print("Got %s" % [pkt.get_string_from_utf8()])
		else:
			var addr = c.get_packet_ip()
			var port = c.get_packet_port()
			print("Got %s from %s %s" % [pkt.get_string_from_utf8(), addr, port])
		c.put_packet(pkt)
	return true`

**Comment by extremety1989** [comment]
@Faless it is still responding to False , do you know what the issue is ?

```
extends SceneTree

const PORT = 4242
const ADDR = "127.0.0.1"


var dtls = true
var clients = {}
var idx = 0
var udp_server = UDPServer.new()
var dtls_server = DTLSServer.new()



func _init():
		var key = load("key.key") 
		var cert = load("cert.crt")
		dtls_server.setup(key, cert, null)
		udp_server.listen(PORT)
		print("Setup: %s" % dtls_server.setup(key, cert, null))
		print("Listen " + str(udp_server.listen(PORT)))
		if udp_server.is_listening():
				connect("idle_frame", self, "process")
		

func process():
		print(udp_server.is_connection_available())
		if udp_server.is_connection_available():
			_take_connection()
		# Clean stale clients
		var to_rem = []
		for k in clients:
			if not _poll_client(clients[k]):
				to_rem.append(k)
		for k in to_rem:
			clients.erase(k)

func _take_connection():
	var key = str(idx)
	idx += 1
	print("take connection")
	if not (key in clients):
		print("Taking connection: %s" % key)
		# Get the UDP connection
		var conn = udp_server.take_connection()
		if dtls:
			# Try to handshake with the UDP peer
			var secure = dtls_server.take_connection(conn)
			if secure.get_status() != PacketPeerDTLS.STATUS_HANDSHAKING:
				idx -= 1
				print("Handshake failed")
			else:
				# 50% of the time under regular conditions (client connecting with no cookie set)
				print("Handshaking with client")
				clients[key] = secure
		else:
			clients[key] = conn

func _poll_client(c):
	if dtls:
		c.poll()
		var status = c.get_status()
		if status != PacketPeerDTLS.STATUS_CONNECTED and status != PacketPeerDTLS.STATUS_HANDSHAKING:
			return false
		if status == PacketPeerDTLS.STATUS_HANDSHAKING:
			return true
	while c.get_available_packet_count() > 0:
		var pkt = c.get_packet()
		if dtls:
			print("Got %s" % [pkt.get_string_from_utf8()])
		else:
			var addr = c.get_packet_ip()
			var port = c.get_packet_port()
			print("Got %s from %s %s" % [pkt.get_string_from_utf8(), addr, port])
		c.put_packet(pkt)
	return true
```
