### ISSUE TITLE
Current repo not working?

### ISSUE THREAD

**Issue by extremety1989** [Faless/gd-udp-dtls-example#2]
i downloaded current repo, also tried new ssl generated (key,cert)
when i host and connect

--- Debugging process started ---
Godot Engine v3.2.2.beta4.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce 940MX/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
Setup: 0
Listen 0
Connect to 127.0.0.1 4433: 0
Taking connection: 0
Handshake failed
Connect to 127.0.0.1 4433: 0

**Comment by Faless** [comment]
Do you get any error in the `Error` tab? It seems to work for me.

**Comment by Faless** [comment]
Also, what gets printed if you change  `_log("Handshake failed")` to `_log("Handshake failed %d" % [secure.get_status()] )`?

**Comment by extremety1989** [comment]
@Faless 
Handshake failed 3

**Comment by Faless** [comment]
So something errors out, do you have any error in the `Error` tab?

**Comment by extremety1989** [comment]
no errors, but when i click again to host i get this

E 0:00:57.120   _setup: This SSL context is already active
  <C++ Error>   Condition "inited" is true. Returned: ERR_ALREADY_IN_USE
  <C++ Source>  modules/mbedtls/ssl_context_mbedtls.cpp:89 @ _setup()
  <Stack Trace> client.gd:29 @ _on_connect_pressed()

**Comment by Faless** [comment]
seems like you are pressing the `connect` button twice.
Did you by any chance change the code?
If not:
1 - open the demo
2 - Press `Host`
3 - Then press `connect` (*once*).
Should work, if it doesn't, check the error again, should be a different one.

**Comment by extremety1989** [comment]
i did not chnage anything, i retried

Setup: 0
Listen 0
Taking connection: 0
Handshake failed 3

**Comment by Faless** [comment]
And nothing in the `error` tab?

**Comment by extremety1989** [comment]
yes nothing

**Comment by extremety1989** [comment]
well except that 
W 0:00:01.714   The argument 'delta' is never used in the function '_process'. If this is intended, prefix it with an underscore: '_delta'
  <C++ Error>   UNUSED_ARGUMENT
  <Source>      client.gd:13

**Comment by Faless** [comment]
Weird, what OS are you on? Can you try running from the command line? You should get more output there (mbedtls debug output)

**Comment by Faless** [comment]
Also, you said you changed the certificate, did you create with the right FQDN? `CN=aserver`? Can you try resetting it to the one shipped with the project?

**Comment by extremety1989** [comment]
windows 10
no i did use same certs that are in repo

**Comment by extremety1989** [comment]
should i generate new certs ?

**Comment by extremety1989** [comment]
well i just generated 
openssl req -x509 -newkey rsa:2048 -nodes -sha256 -subj '/CN=aserver' -keyout localhost-privkey.key -out localhost-cert.crt

got same message 

Setup: 0
Listen 0
Taking connection: 0
Handshake failed

**Comment by extremety1989** [comment]
i used certs from repo and newely created on nodejs server they work !!!! ,but i do not understand why they do not work on Godot ?

**Comment by Faless** [comment]
It appears to be a Windows specific socket issue.

**Comment by extremety1989** [comment]
@Faless hope this going to be fixed
